<a href="https://colab.research.google.com/github/Alex-Roberts27/SerranoRNASeqData/blob/main/SerranoRNASeq.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%pip install pydeseq2
from pydeseq2.dds import DeseqDataSet
from pydeseq2.ds import DeseqStats
import pandas as pd

Requirement already satisfied: pydeseq2 in /usr/local/lib/python3.12/dist-packages (0.5.4)
Requirement already satisfied: anndata>=0.11.0 in /usr/local/lib/python3.12/dist-packages (from pydeseq2) (0.12.16)
Requirement already satisfied: formulaic-contrasts>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from pydeseq2) (1.0.0)
Requirement already satisfied: formulaic>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from pydeseq2) (1.2.1)
Requirement already satisfied: matplotlib>=3.9.0 in /usr/local/lib/python3.12/dist-packages (from pydeseq2) (3.10.0)
Requirement already satisfied: numpy>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pydeseq2) (2.0.2)
Requirement already satisfied: pandas>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from pydeseq2) (2.2.2)
Requirement already satisfied: scikit-learn>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from pydeseq2) (1.6.1)
Requirement already satisfied: scipy>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from pydeseq2) (1.16.3)
Requirement already satisfied: array-api-compat>=1.7.1 in /usr/local/lib/python3.12/dist-packages (from anndata>=0.11.0->pydeseq2) (1.14.0)
Requirement already satisfied: h5py>=3.8 in /usr/local/lib/python3.12/dist-packages (from anndata>=0.11.0->pydeseq2) (3.16.0)
Requirement already satisfied: legacy-api-wrap in /usr/local/lib/python3.12/dist-packages (from anndata>=0.11.0->pydeseq2) (1.5)
Requirement already satisfied: natsort in /usr/local/lib/python3.12/dist-packages (from anndata>=0.11.0->pydeseq2) (8.4.0)
Requirement already satisfied: packaging>=24.2 in /usr/local/lib/python3.12/dist-packages (from anndata>=0.11.0->pydeseq2) (26.1)
Requirement already satisfied: scverse-misc>=0.0.3 in /usr/local/lib/python3.12/dist-packages (from anndata>=0.11.0->pydeseq2) (0.0.7)
Requirement already satisfied: zarr!=3.0.*,>=2.18.7 in /usr/local/lib/python3.12/dist-packages (from anndata>=0.11.0->pydeseq2) (3.2.1)
Requirement already satisfied: interface-meta>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from formulaic>=1.0.2->pydeseq2) (2.0.1)
Requirement already satisfied: narwhals>=1.17 in /usr/local/lib/python3.12/dist-packages (from formulaic>=1.0.2->pydeseq2) (2.20.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.12/dist-packages (from formulaic>=1.0.2->pydeseq2) (4.15.0)
Requirement already satisfied: wrapt>=1.0 in /usr/local/lib/python3.12/dist-packages (from formulaic>=1.0.2->pydeseq2) (2.1.2)
Requirement already satisfied: session-info in /usr/local/lib/python3.12/dist-packages (from formulaic-contrasts>=0.2.0->pydeseq2) (1.0.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9.0->pydeseq2) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9.0->pydeseq2) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9.0->pydeseq2) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9.0->pydeseq2) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9.0->pydeseq2) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9.0->pydeseq2) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9.0->pydeseq2) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->pydeseq2) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->pydeseq2) (2026.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.4.0->pydeseq2) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.4.0->pydeseq2) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.9.0->pydeseq2) (1.17.0)
Requirement already satisfied: session-info2 in /usr/local/lib/python3.12/dist-packages (from scverse-misc>=0.0.3->anndata>=0.11.0->pydeseq2) (0.4.1)
Requirement already satisfied: donfig>=0.8 in /usr/local/lib/python3.12/dist-packages (from zarr!=3.0.*,>=2.18.7->anndata>=0.11.0->pydeseq2) (0.8.1.post1)
Requirement already satisfied: google-crc32c>=1.5 in /usr/local/lib/python3.12/dist-packages (from zarr!=3.0.*,>=2.18.7->anndata>=0.11.0->pydeseq2) (1.8.0)
Requirement already satisfied: numcodecs>=0.14 in /usr/local/lib/python3.12/dist-packages (from zarr!=3.0.*,>=2.18.7->anndata>=0.11.0->pydeseq2) (0.16.5)
Requirement already satisfied: stdlib_list in /usr/local/lib/python3.12/dist-packages (from session-info->formulaic-contrasts>=0.2.0->pydeseq2) (0.12.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from donfig>=0.8->zarr!=3.0.*,>=2.18.7->anndata>=0.11.0->pydeseq2) (6.0.3)

In [ ]:
counts = pd.read_csv('isoform_exp_names2.csv')
counts

,Gene_Name,test_id,gene_id,gene,locus,sample_1,sample_2,status,value_1,value_2,log2(fold_change),test_stat,p_value,q_value,significant
0,Lypla1,TCONS_00000001,XLOC_000001,NM_008866,chr1:4807892-4846735,MockIFN,T1L-IFN,OK,31.891900,26.145800,-0.286613,-1.500670,0.03475,0.115197,no
1,UNKNOWN,TCONS_00000002,XLOC_000002,-,chr1:4850638-4851240,MockIFN,T1L-IFN,OK,0.122733,0.482925,1.976280,1.368630,0.09020,0.238539,no
2,Tcea1,TCONS_00000003,XLOC_000003,NM_001159750,chr1:4857693-4897909,MockIFN,T1L-IFN,OK,18.850100,21.697700,0.202966,0.462447,0.51150,0.647648,no
3,Tcea1,TCONS_00000004,XLOC_000003,NM_011541,chr1:4857693-4897909,MockIFN,T1L-IFN,OK,88.239300,86.410100,-0.030221,-0.145027,0.83100,0.886051,no
4,Tcea1,TCONS_00000005,XLOC_000003,NM_001159751,chr1:4857693-4897909,MockIFN,T1L-IFN,NOTEST,0.115223,0.060123,-0.938440,0.000000,1.00000,1.000000,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60700,Gm20854,TCONS_00060758,XLOC_031798,NM_001160131,chrY:83789753-83927911,MockIFN,T1L-IFN,NOTEST,0.000000,0.000000,0.000000,0.000000,1.00000,1.000000,no
60701,Gm20854,TCONS_00060759,XLOC_031799,NM_001160131,chrY:85528524-85529519,MockIFN,T1L-IFN,NOTEST,0.000000,0.000000,0.000000,0.000000,1.00000,1.000000,no
60702,UNKNOWN,TCONS_00060760,XLOC_031800,-,chrY:90739963-90740251,MockIFN,T1L-IFN,OK,0.000000,1.191100,inf,NaN,0.00045,0.003049,yes
60703,UNKNOWN,TCONS_00060761,XLOC_031801,-,chrY:90741060-90741352,MockIFN,T1L-IFN,OK,1.427630,4.903170,1.780100,1.380410,0.10410,0.263303,no
60704,UNKNOWN,TCONS_00060762,XLOC_031802,-,chrY:90741530-90741793,MockIFN,T1L-IFN,OK,1.659960,5.995400,1.852710,1.274540,0.09230,0.242540,no

In [ ]:
#remove test_id column
counts = counts.drop(columns=['test_id'])
counts
#remove gene_id column
counts = counts.drop(columns=['gene_id'])
counts
#remove locus column
counts = counts.drop(columns=['locus'])
counts

,Gene_Name,gene,sample_1,sample_2,status,value_1,value_2,log2(fold_change),test_stat,p_value,q_value,significant
0,Lypla1,NM_008866,MockIFN,T1L-IFN,OK,31.891900,26.145800,-0.286613,-1.500670,0.03475,0.115197,no
1,UNKNOWN,-,MockIFN,T1L-IFN,OK,0.122733,0.482925,1.976280,1.368630,0.09020,0.238539,no
2,Tcea1,NM_001159750,MockIFN,T1L-IFN,OK,18.850100,21.697700,0.202966,0.462447,0.51150,0.647648,no
3,Tcea1,NM_011541,MockIFN,T1L-IFN,OK,88.239300,86.410100,-0.030221,-0.145027,0.83100,0.886051,no
4,Tcea1,NM_001159751,MockIFN,T1L-IFN,NOTEST,0.115223,0.060123,-0.938440,0.000000,1.00000,1.000000,no
...,...,...,...,...,...,...,...,...,...,...,...,...
60700,Gm20854,NM_001160131,MockIFN,T1L-IFN,NOTEST,0.000000,0.000000,0.000000,0.000000,1.00000,1.000000,no
60701,Gm20854,NM_001160131,MockIFN,T1L-IFN,NOTEST,0.000000,0.000000,0.000000,0.000000,1.00000,1.000000,no
60702,UNKNOWN,-,MockIFN,T1L-IFN,OK,0.000000,1.191100,inf,NaN,0.00045,0.003049,yes
60703,UNKNOWN,-,MockIFN,T1L-IFN,OK,1.427630,4.903170,1.780100,1.380410,0.10410,0.263303,no
60704,UNKNOWN,-,MockIFN,T1L-IFN,OK,1.659960,5.995400,1.852710,1.274540,0.09230,0.242540,no

In [ ]:
#remove ending columns
columns_to_drop = [
    'status',
    'log2(fold_change)',
    'test_stat',
    'p_value',
    'q_value',
    'significant'
]
counts = counts.drop(columns=columns_to_drop)
counts

      Gene_Name          gene sample_1 sample_2    value_1    value_2
0        Lypla1     NM_008866  MockIFN  T1L-IFN  31.891900  26.145800
1       UNKNOWN             -  MockIFN  T1L-IFN   0.122733   0.482925
2         Tcea1  NM_001159750  MockIFN  T1L-IFN  18.850100  21.697700
3         Tcea1     NM_011541  MockIFN  T1L-IFN  88.239300  86.410100
4         Tcea1  NM_001159751  MockIFN  T1L-IFN   0.115223   0.060123
...         ...           ...      ...      ...        ...        ...
60700   Gm20854  NM_001160131  MockIFN  T1L-IFN   0.000000   0.000000
60701   Gm20854  NM_001160131  MockIFN  T1L-IFN   0.000000   0.000000
60702   UNKNOWN             -  MockIFN  T1L-IFN   0.000000   1.191100
60703   UNKNOWN             -  MockIFN  T1L-IFN   1.427630   4.903170
60704   UNKNOWN             -  MockIFN  T1L-IFN   1.659960   5.995400

[60705 rows x 6 columns]

In [ ]:
#remove UNKNOWN from Gene_name
counts = counts[counts.Gene_Name != 'UNKNOWN']
counts

      Gene_Name          gene sample_1 sample_2    value_1    value_2
0        Lypla1     NM_008866  MockIFN  T1L-IFN  31.891900  26.145800
2         Tcea1  NM_001159750  MockIFN  T1L-IFN  18.850100  21.697700
3         Tcea1     NM_011541  MockIFN  T1L-IFN  88.239300  86.410100
4         Tcea1  NM_001159751  MockIFN  T1L-IFN   0.115223   0.060123
7       Atp6v1h     NM_133826  MockIFN  T1L-IFN   0.070314   0.000000
...         ...           ...      ...      ...        ...        ...
60697     Ssty2     NM_023546  MockIFN  T1L-IFN   0.000000   0.000000
60698   Gm20806  NM_001160135  MockIFN  T1L-IFN   0.000000   0.000000
60699   Gm20747  NM_001025241  MockIFN  T1L-IFN   0.000000   0.000000
60700   Gm20854  NM_001160131  MockIFN  T1L-IFN   0.000000   0.000000
60701   Gm20854  NM_001160131  MockIFN  T1L-IFN   0.000000   0.000000

[51568 rows x 6 columns]

In [ ]:
#remove genes where value_1 equal 0
counts = counts[counts.value_1 != 0]
counts

      Gene_Name          gene sample_1 sample_2    value_1     value_2
0        Lypla1     NM_008866  MockIFN  T1L-IFN  31.891900   26.145800
2         Tcea1  NM_001159750  MockIFN  T1L-IFN  18.850100   21.697700
3         Tcea1     NM_011541  MockIFN  T1L-IFN  88.239300   86.410100
4         Tcea1  NM_001159751  MockIFN  T1L-IFN   0.115223    0.060123
7       Atp6v1h     NM_133826  MockIFN  T1L-IFN   0.070314    0.000000
...         ...           ...      ...      ...        ...         ...
60579     Vamp7     NM_011515  MockIFN  T1L-IFN   5.145230    3.294300
60582     Uba1y     NM_011667  MockIFN  T1L-IFN   0.012620    0.044779
60632     Erdr1     NM_133362  MockIFN  T1L-IFN  11.515200    3.788260
60633     Erdr1     NM_133362  MockIFN  T1L-IFN   0.449291    1.601610
60635     Erdr1     NM_133362  MockIFN  T1L-IFN  86.140200  112.686000

[38120 rows x 6 columns]

In [ ]:
#remove genes where value_2 equal 0
counts = counts[counts.value_2 != 0]
counts

      Gene_Name          gene sample_1 sample_2    value_1     value_2
0        Lypla1     NM_008866  MockIFN  T1L-IFN  31.891900   26.145800
2         Tcea1  NM_001159750  MockIFN  T1L-IFN  18.850100   21.697700
3         Tcea1     NM_011541  MockIFN  T1L-IFN  88.239300   86.410100
4         Tcea1  NM_001159751  MockIFN  T1L-IFN   0.115223    0.060123
8       Atp6v1h     NM_133826  MockIFN  T1L-IFN   0.050023    0.713956
...         ...           ...      ...      ...        ...         ...
60579     Vamp7     NM_011515  MockIFN  T1L-IFN   5.145230    3.294300
60582     Uba1y     NM_011667  MockIFN  T1L-IFN   0.012620    0.044779
60632     Erdr1     NM_133362  MockIFN  T1L-IFN  11.515200    3.788260
60633     Erdr1     NM_133362  MockIFN  T1L-IFN   0.449291    1.601610
60635     Erdr1     NM_133362  MockIFN  T1L-IFN  86.140200  112.686000

[35593 rows x 6 columns]

In [ ]:
%pip install mygene

Requirement already satisfied: mygene in /usr/local/lib/python3.12/dist-packages (3.2.2)
Requirement already satisfied: biothings-client>=0.2.6 in /usr/local/lib/python3.12/dist-packages (from mygene) (0.5.0)
Requirement already satisfied: httpx>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from biothings-client>=0.2.6->mygene) (0.28.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.0->biothings-client>=0.2.6->mygene) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.0->biothings-client>=0.2.6->mygene) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.0->biothings-client>=0.2.6->mygene) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.0->biothings-client>=0.2.6->mygene) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.25.0->biothings-client>=0.2.6->mygene) (0.16.0)
Requirement already satisfied: typing_extensions>=4.5 in /usr/local/lib/python3.12/dist-packages (from anyio->httpx>=0.25.0->biothings-client>=0.2.6->mygene) (4.15.0)

In [ ]:
import mygene

In [ ]:
mg = mygene.MyGeneInfo()

# 2. Use the existing 'gene_names' list extracted from your DataFrame
# The 'counts' DataFrame from previous cells already has the desired columns.

# 3. Query Ensembl IDs
# scopes='symbol' tells the API your input is a gene symbol
# fields='ensembl.gene' specifies you want the Ensembl Gene ID
results = mg.querymany(gene_names,
                       scopes='symbol',
                       fields='ensembl.gene',
                       species='human',
                       as_dataframe=True)

# 4. Merge back to your original DataFrame. We need to handle duplicates in results before merging.
# First, remove duplicate Gene_Name entries from the original 'counts' for a clean merge base.
# We will merge the ensembl.gene column from the results back into the counts dataframe.
# Since 'results' might have multiple ensembl.gene entries for one symbol, let's pick the first one found.
results_deduplicated = results.groupby('query')['ensembl.gene'].first().reset_index()
results_deduplicated = results_deduplicated.rename(columns={'query': 'Gene_Name'})

# Merge based on Gene_Name
df = counts.merge(results_deduplicated[['Gene_Name', 'ensembl.gene']], on='Gene_Name', how='left')

print(df)

INFO:biothings.client:querying 1-1000 ...
INFO:biothings.client:querying 1001-2000 ...
INFO:biothings.client:querying 2001-3000 ...
INFO:biothings.client:querying 3001-4000 ...
INFO:biothings.client:querying 4001-5000 ...
INFO:biothings.client:querying 5001-6000 ...
INFO:biothings.client:querying 6001-7000 ...
INFO:biothings.client:querying 7001-8000 ...
INFO:biothings.client:querying 8001-9000 ...
INFO:biothings.client:querying 9001-10000 ...
INFO:biothings.client:querying 10001-11000 ...
INFO:biothings.client:querying 11001-12000 ...
INFO:biothings.client:querying 12001-13000 ...
INFO:biothings.client:querying 13001-14000 ...
INFO:biothings.client:querying 14001-15000 ...
INFO:biothings.client:querying 15001-16000 ...
INFO:biothings.client:querying 16001-17000 ...
INFO:biothings.client:querying 17001-18000 ...
INFO:biothings.client:querying 18001-19000 ...
INFO:biothings.client:querying 19001-20000 ...
INFO:biothings.client:querying 20001-21000 ...
INFO:biothings.client:querying 21001-22000 ...
INFO:biothings.client:querying 22001-23000 ...
INFO:biothings.client:querying 23001-24000 ...
INFO:biothings.client:querying 24001-25000 ...
INFO:biothings.client:querying 25001-26000 ...
INFO:biothings.client:querying 26001-27000 ...
INFO:biothings.client:querying 27001-28000 ...
INFO:biothings.client:querying 28001-29000 ...
INFO:biothings.client:querying 29001-30000 ...
INFO:biothings.client:querying 30001-31000 ...
INFO:biothings.client:querying 31001-32000 ...
INFO:biothings.client:querying 32001-33000 ...
INFO:biothings.client:querying 33001-34000 ...
INFO:biothings.client:querying 34001-35000 ...
INFO:biothings.client:querying 35001-35593 ...
INFO:biothings.client:Finished.
WARNING:biothings.client:7857 input query terms found dup hits:	[('Tcea1', 3), ('Atp6v1h', 5), ('Rb1cc1', 4), ('St18', 5), ('Pcmtd1', 3), ('Adhfe1', 2), ('Sgk3', 2)
WARNING:biothings.client:6261 input query terms found no hit:	['3110035E14Rik', '1700034P13Rik', 'A830018L16Rik', 'A830018L16Rik', 'A830018L16Rik', 'Gm17644', 'D0
INFO:biothings.client:Pass "returnall=True" to return complete lists of duplicate or missing query terms.

      Gene_Name          gene sample_1 sample_2    value_1     value_2  \
0        Lypla1     NM_008866  MockIFN  T1L-IFN  31.891900   26.145800
1         Tcea1  NM_001159750  MockIFN  T1L-IFN  18.850100   21.697700
2         Tcea1     NM_011541  MockIFN  T1L-IFN  88.239300   86.410100
3         Tcea1  NM_001159751  MockIFN  T1L-IFN   0.115223    0.060123
4       Atp6v1h     NM_133826  MockIFN  T1L-IFN   0.050023    0.713956
...         ...           ...      ...      ...        ...         ...
35588     Vamp7     NM_011515  MockIFN  T1L-IFN   5.145230    3.294300
35589     Uba1y     NM_011667  MockIFN  T1L-IFN   0.012620    0.044779
35590     Erdr1     NM_133362  MockIFN  T1L-IFN  11.515200    3.788260
35591     Erdr1     NM_133362  MockIFN  T1L-IFN   0.449291    1.601610
35592     Erdr1     NM_133362  MockIFN  T1L-IFN  86.140200  112.686000

          ensembl.gene
0      ENSG00000120992
1      ENSG00000187735
2      ENSG00000187735
3      ENSG00000187735
4      ENSG00000047249
...                ...
35588             None
35589             None
35590             None
35591             None
35592             None

[35593 rows x 7 columns]

In [ ]:
df

,Gene_Name,gene,sample_1,sample_2,value_1,value_2,ensembl.gene
0,Lypla1,NM_008866,MockIFN,T1L-IFN,31.891900,26.145800,ENSG00000120992
1,Tcea1,NM_001159750,MockIFN,T1L-IFN,18.850100,21.697700,ENSG00000187735
2,Tcea1,NM_011541,MockIFN,T1L-IFN,88.239300,86.410100,ENSG00000187735
3,Tcea1,NM_001159751,MockIFN,T1L-IFN,0.115223,0.060123,ENSG00000187735
4,Atp6v1h,NM_133826,MockIFN,T1L-IFN,0.050023,0.713956,ENSG00000047249
...,...,...,...,...,...,...,...
35588,Vamp7,NM_011515,MockIFN,T1L-IFN,5.145230,3.294300,None
35589,Uba1y,NM_011667,MockIFN,T1L-IFN,0.012620,0.044779,None
35590,Erdr1,NM_133362,MockIFN,T1L-IFN,11.515200,3.788260,None
35591,Erdr1,NM_133362,MockIFN,T1L-IFN,0.449291,1.601610,None
35592,Erdr1,NM_133362,MockIFN,T1L-IFN,86.140200,112.686000,None

In [ ]:
#put ensembl.gene column to the left of Gene_Name
df = df[['ensembl.gene', 'value_1', 'value_2']]
df

          ensembl.gene    value_1     value_2
0      ENSG00000120992  31.891900   26.145800
1      ENSG00000187735  18.850100   21.697700
2      ENSG00000187735  88.239300   86.410100
3      ENSG00000187735   0.115223    0.060123
4      ENSG00000047249   0.050023    0.713956
...                ...        ...         ...
35588             None   5.145230    3.294300
35589             None   0.012620    0.044779
35590             None  11.515200    3.788260
35591             None   0.449291    1.601610
35592             None  86.140200  112.686000

[35593 rows x 3 columns]

In [ ]:
#remove rows where ensembl.gene is None
df = df.dropna(subset=['ensembl.gene'])
df

          ensembl.gene    value_1    value_2
0      ENSG00000120992  31.891900  26.145800
1      ENSG00000187735  18.850100  21.697700
2      ENSG00000187735  88.239300  86.410100
3      ENSG00000187735   0.115223   0.060123
4      ENSG00000047249   0.050023   0.713956
...                ...        ...        ...
35580  ENSG00000004961   0.582569   0.011002
35581  ENSG00000004961  11.123700   5.781910
35582  ENSG00000004961   2.532940   1.453070
35583  ENSG00000004961   7.031120   7.585820
35585  ENSG00000185973   0.003914   0.013848

[27552 rows x 3 columns]

In [ ]:
#rename column ensembl.gene to gene_id
df = df.rename(columns={'ensembl.gene': 'gene_id'})
df
#rename column value_1 to MockIFN
df = df.rename(columns={'value_1': 'MockIFN'})
df
#rename column value_2 to T1L-IFN
df = df.rename(columns={'value_2': 'T1L-IFN'})
df

               gene_id    MockIFN    T1L-IFN
0      ENSG00000120992  31.891900  26.145800
1      ENSG00000187735  18.850100  21.697700
2      ENSG00000187735  88.239300  86.410100
3      ENSG00000187735   0.115223   0.060123
4      ENSG00000047249   0.050023   0.713956
...                ...        ...        ...
35580  ENSG00000004961   0.582569   0.011002
35581  ENSG00000004961  11.123700   5.781910
35582  ENSG00000004961   2.532940   1.453070
35583  ENSG00000004961   7.031120   7.585820
35585  ENSG00000185973   0.003914   0.013848

[27552 rows x 3 columns]

In [ ]:
counts = df.set_index('gene_id')
counts

                   MockIFN    T1L-IFN
gene_id
ENSG00000120992  31.891900  26.145800
ENSG00000187735  18.850100  21.697700
ENSG00000187735  88.239300  86.410100
ENSG00000187735   0.115223   0.060123
ENSG00000047249   0.050023   0.713956
...                    ...        ...
ENSG00000004961   0.582569   0.011002
ENSG00000004961  11.123700   5.781910
ENSG00000004961   2.532940   1.453070
ENSG00000004961   7.031120   7.585820
ENSG00000185973   0.003914   0.013848

[27552 rows x 2 columns]

In [ ]:
counts = counts.T
counts

gene_id,ENSG00000120992,ENSG00000187735,ENSG00000187735,ENSG00000187735,ENSG00000047249,ENSG00000047249,ENSG00000047249,ENSG00000047249,ENSG00000047249,ENSG00000023287,...,ENSG00000196664,ENSG00000101911,ENSG00000101911,ENSG00000005302,ENSG00000005302,ENSG00000004961,ENSG00000004961,ENSG00000004961,ENSG00000004961,ENSG00000185973
MockIFN,31.8919,18.8501,88.2393,0.115223,0.050023,8.97262,15.4580,24.7447,5.04715,0.260910,...,0.711607,5.97375,18.64740,2.02405,28.8040,0.582569,11.12370,2.53294,7.03112,0.003914
T1L-IFN,26.1458,21.6977,86.4101,0.060123,0.713956,16.66480,18.6041,37.6230,5.46356,0.001054,...,0.063533,4.14561,8.86501,3.16663,25.4058,0.011002,5.78191,1.45307,7.58582,0.013848

In [ ]:
counts.isnull().sum()

gene_id
ENSG00000120992    0
ENSG00000187735    0
ENSG00000187735    0
ENSG00000187735    0
ENSG00000047249    0
                  ..
ENSG00000004961    0
ENSG00000004961    0
ENSG00000004961    0
ENSG00000004961    0
ENSG00000185973    0
Length: 27552, dtype: int64

In [ ]:
metadata = pd.DataFrame(zip(counts.index, ['Mock','T1L']),
                        columns = ['Sample', 'Condition'])

In [ ]:
metadata = metadata.set_index('Sample')
metadata

        Condition
Sample
MockIFN      Mock
T1L-IFN       T1L

In [ ]:
counts = counts.round().astype(int)
dds = DeseqDataSet(counts=counts,
            metadata=metadata,
            design="~Condition")

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1884: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

In [ ]:
dds.deseq2()

Using None as control genes, passed at DeseqDataSet initialization

Fitting size factors...
... done in 0.01 seconds.

ValueError: The number of samples and the number of design variables are equal, i.e., there are no replicates to estimate the dispersion. Please use a design with fewer variables.